import path from 'node:path';
import * as engineRuntime from '@zachariahredfield/playbook-engine';
import { ExitCode } from '../lib/cliContract.js';
import { emitJsonOutput, writeJsonArtifact } from '../lib/jsonArtifact.js';
import { printCommandHelp } from '../lib/commandSurface.js';
const engine = engineRuntime;
const DEFAULT_OUT_FILE = '.playbook/test-fix-plan.json';
const readTriageArtifact = (cwd, fromTriage) => {
    if (!fromTriage) {
        throw new Error('playbook test-fix-plan: --from-triage <artifact> is required.');
    }
    const absolutePath = path.resolve(cwd, fromTriage);
    const artifact = engine.readArtifactJson(absolutePath);
    if (artifact.kind !== 'test-triage' || artifact.command !== 'test-triage' || !Array.isArray(artifact.findings)) {
        throw new Error('playbook test-fix-plan: invalid test-triage artifact.');
    }
    return artifact;
};
const renderText = (artifact, outFile) => {
    const lines = [
        'Test fix plan',
        '─────────────',
        `Source artifact: ${artifact.source.path ?? '(stdin)'}`,
        `Wrote artifact: ${outFile}`,
        `Eligible findings: ${artifact.summary.eligible_findings}`,
        `Excluded findings: ${artifact.summary.excluded_findings}`,
        `Auto-fix tasks: ${artifact.summary.auto_fix_tasks}`
    ];
    if (artifact.tasks.length > 0) {
        lines.push('', 'Tasks');
        for (const task of artifact.tasks) {
            lines.push(`- ${task.id} ${task.ruleId} ${task.file ?? '(missing file)'}`);
            lines.push(`  ${task.action}`);
        }
    }
    if (artifact.excluded.length > 0) {
        lines.push('', 'Excluded');
        for (const exclusion of artifact.excluded) {
            lines.push(`- finding ${exclusion.finding_index + 1}: ${exclusion.reason}`);
            lines.push(`  ${exclusion.summary}`);
        }
    }
    return lines.join('\n');
};
export const runTestFixPlan = async (cwd, options) => {
    if (options.help) {
        printCommandHelp({
            usage: 'playbook test-fix-plan --from-triage <artifact> [--out <path>] [--json]',
            description: 'Build a bounded apply-compatible remediation plan from a deterministic test-triage artifact.',
            options: [
                '--from-triage <artifact>  Read a test-triage artifact generated by `playbook test-triage`',
                `--out <path>              Write the generated plan artifact (default ${DEFAULT_OUT_FILE})`,
                '--json                    Print the stable test-fix-plan artifact as JSON',
                '--help                    Show help'
            ],
            artifacts: [DEFAULT_OUT_FILE]
        });
        return ExitCode.Success;
    }
    try {
        const triage = readTriageArtifact(cwd, options.fromTriage);
        const artifact = engine.buildTestFixPlanArtifact(triage);
        const outFile = options.outFile ?? DEFAULT_OUT_FILE;
        writeJsonArtifact(cwd, outFile, artifact, 'test-fix-plan');
        if (options.format === 'json') {
            emitJsonOutput({ cwd, command: 'test-fix-plan', payload: artifact });
            return ExitCode.Success;
        }
        if (!options.quiet) {
            console.log(renderText(artifact, outFile));
        }
        return ExitCode.Success;
    }
    catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        if (options.format === 'json') {
            console.log(JSON.stringify({ schemaVersion: '1.0', command: 'test-fix-plan', error: message }, null, 2));
        }
        else {
            console.error(message);
        }
        return ExitCode.Failure;
    }
};
//# sourceMappingURL=testFixPlan.js.map